import { ReportJson } from "./types";

// Generate a simple text-based PDF using raw PDF syntax
// This avoids external dependencies while working in a Worker environment
export function generatePDF(report: ReportJson): Uint8Array {
  const lines: string[] = [];

  const verdictColor = getVerdictColor(report.overall.verdict);

  // Build text content
  lines.push("OFFER INTEGRITY REPORT");
  lines.push("=" .repeat(60));
  lines.push(`Offer: ${report.meta.offerName}`);
  lines.push(`Price: $${report.meta.price.toLocaleString()} USD`);
  lines.push(`Generated: ${new Date(report.meta.generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  lines.push("");
  lines.push("OVERALL SCORE");
  lines.push("-".repeat(40));
  lines.push(`Score: ${report.overall.scoreTotal}/70 (${report.overall.scorePercent}%)`);
  lines.push(`Verdict: ${report.overall.verdict}`);
  lines.push("");
  lines.push("TOP STRENGTHS:");
  report.overall.topStrengths.forEach((s, i) => lines.push(`  ${i + 1}. ${s}`));
  lines.push("");
  lines.push("TOP RISKS:");
  report.overall.topRisks.forEach((r, i) => lines.push(`  ${i + 1}. ${r}`));
  lines.push("");
  lines.push("PILLAR SCORES");
  lines.push("=" .repeat(60));

  report.pillars.forEach((p) => {
    lines.push("");
    lines.push(`${p.name.toUpperCase()} — ${p.score}/10`);
    lines.push(scoreBar(p.score));
    lines.push(`Why it matters: ${p.whyItMatters}`);
    if (p.whatYouHave.length > 0) {
      lines.push("What you have:");
      p.whatYouHave.forEach((w) => lines.push(`  + ${w}`));
    }
    if (p.gaps.length > 0) {
      lines.push("Gaps:");
      p.gaps.forEach((g) => lines.push(`  - ${g}`));
    }
    if (p.recommendations.length > 0) {
      lines.push("Recommendations:");
      p.recommendations.forEach((r) => lines.push(`  [${r.priority}] ${r.action}`));
    }
    if (p.riskFlags.length > 0) {
      lines.push("Risk Flags:");
      p.riskFlags.forEach((rf) => lines.push(`  [${rf.level}] ${rf.flag}: ${rf.reason}`));
    }
  });

  lines.push("");
  lines.push("=" .repeat(60));
  lines.push("30-DAY ACTION PLAN");
  lines.push("=" .repeat(60));
  lines.push("");
  lines.push("NEXT 7 DAYS:");
  report.recommendationPlan.next7Days.forEach((a, i) => lines.push(`  ${i + 1}. ${a}`));
  lines.push("");
  lines.push("NEXT 14 DAYS:");
  report.recommendationPlan.next14Days.forEach((a, i) => lines.push(`  ${i + 1}. ${a}`));
  lines.push("");
  lines.push("NEXT 30 DAYS:");
  report.recommendationPlan.next30Days.forEach((a, i) => lines.push(`  ${i + 1}. ${a}`));
  lines.push("");
  lines.push("=" .repeat(60));
  lines.push("Generated by OfferIntegrity.io");

  // V2 Intelligence summary (appended if present)
  if ((report as any).v2) {
    const v2 = (report as any).v2;
    lines.push("");
    lines.push("=".repeat(60));
    lines.push("V2 INTELLIGENCE SUMMARY");
    lines.push("=".repeat(60));
    if (v2.closeProbabilityRange)
      lines.push(`  Close Probability Range : ${v2.closeProbabilityRange}`);
    if (v2.riskBand)
      lines.push(`  Overall Risk Band       : ${v2.riskBand}`);
    if (v2.supportedPriceBand)
      lines.push(`  Supported Price Band    : ${v2.supportedPriceBand}`);
    if (v2.fragilityLabel)
      lines.push(`  Offer Fragility         : ${v2.fragilityLabel}`);
    lines.push("");
  }

  const textContent = lines.join("\n");

  // Build minimal valid PDF
  return buildMinimalPDF(textContent, report);
}

function scoreBar(score: number): string {
  const filled = Math.round(score);
  const empty = 10 - filled;
  return `  [${"█".repeat(filled)}${"░".repeat(empty)}] ${score}/10`;
}

function getVerdictColor(verdict: string): string {
  switch (verdict) {
    case "Launch Ready": return "0.2 0.7 0.3";
    case "Refine Before Scaling": return "0.9 0.7 0.1";
    case "High Risk": return "0.9 0.4 0.1";
    case "Do Not Launch": return "0.8 0.1 0.1";
    default: return "0.5 0.5 0.5";
  }
}

function buildMinimalPDF(text: string, report: ReportJson): Uint8Array {
  // We'll build a proper minimal PDF from scratch
  const encoder = new TextEncoder();

  const pageWidth = 612;
  const pageHeight = 792;
  const margin = 50;
  const lineHeight = 14;
  const fontSize = 10;
  const maxWidth = pageWidth - margin * 2;

  // Split text into lines that fit
  const rawLines = text.split("\n");
  const allLines: string[] = [];
  for (const line of rawLines) {
    // Rough char width estimate: ~6px per char at font size 10
    const maxChars = Math.floor(maxWidth / 5.5);
    if (line.length <= maxChars) {
      allLines.push(line);
    } else {
      // Word wrap
      const words = line.split(" ");
      let current = "";
      for (const word of words) {
        if ((current + " " + word).trim().length <= maxChars) {
          current = (current + " " + word).trim();
        } else {
          if (current) allLines.push(current);
          current = word;
        }
      }
      if (current) allLines.push(current);
    }
  }

  // Paginate
  const linesPerPage = Math.floor((pageHeight - margin * 2) / lineHeight);
  const pages: string[][] = [];
  for (let i = 0; i < allLines.length; i += linesPerPage) {
    pages.push(allLines.slice(i, i + linesPerPage));
  }

  // Build PDF objects
  const objects: string[] = [];
  const offsets: number[] = [];
  let pos = 0;

  function addObj(content: string): number {
    const idx = objects.length + 1;
    offsets.push(pos);
    const obj = `${idx} 0 obj\n${content}\nendobj\n`;
    objects.push(obj);
    pos += encoder.encode(obj).length;
    return idx;
  }

  // We'll accumulate bytes
  const parts: string[] = [];
  const header = "%PDF-1.4\n";
  parts.push(header);
  pos = encoder.encode(header).length;

  // Reset and use parts array approach
  // Simpler: build as string then convert
  let pdf = "%PDF-1.4\n";
  const xrefOffsets: number[] = [];

  function escPDF(s: string): string {
    return s
      .replace(/\\/g, "\\\\")
      .replace(/\(/g, "\\(")
      .replace(/\)/g, "\\)");
  }

  const pdfObjects: Array<{ id: number; content: string }> = [];
  let objId = 1;

  // Font
  const fontId = objId++;
  pdfObjects.push({
    id: fontId,
    content: `<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`,
  });

  const fontBoldId = objId++;
  pdfObjects.push({
    id: fontBoldId,
    content: `<< /Type /Font /Subtype /Type1 /BaseFont /Courier-Bold >>`,
  });

  // Page content objects and page objects
  const pageIds: number[] = [];
  const contentIds: number[] = [];

  for (const pageLines of pages) {
    let stream = "BT\n";
    stream += `/F1 10 Tf\n`;
    stream += `${margin} ${pageHeight - margin - lineHeight} Td\n`;
    stream += `${lineHeight} TL\n`;

    for (const line of pageLines) {
      // Bold for headers (lines with = or starting with uppercase words)
      const isBold = line.startsWith("=") || line.startsWith("-") ||
        /^[A-Z][A-Z\s&\/—]+:?$/.test(line.trim());

      if (isBold) {
        stream += `/F2 10 Tf\n`;
      } else {
        stream += `/F1 10 Tf\n`;
      }
      stream += `(${escPDF(line)}) Tj T*\n`;
    }
    stream += "ET";

    const contentId = objId++;
    const streamBytes = encoder.encode(stream);
    pdfObjects.push({
      id: contentId,
      content: `<< /Length ${streamBytes.length} >>\nstream\n${stream}\nendstream`,
    });
    contentIds.push(contentId);

    const pageId = objId++;
    pageIds.push(pageId);
  }

  const pagesId = objId++;
  const catalogId = objId++;

  // Add page objects
  for (let i = 0; i < pages.length; i++) {
    pdfObjects.push({
      id: pageIds[i],
      content: `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents ${contentIds[i]} 0 R /Resources << /Font << /F1 ${fontId} 0 R /F2 ${fontBoldId} 0 R >> >> >>`,
    });
  }

  const pageRefs = pageIds.map((id) => `${id} 0 R`).join(" ");
  pdfObjects.push({
    id: pagesId,
    content: `<< /Type /Pages /Kids [${pageRefs}] /Count ${pageIds.length} >>`,
  });

  pdfObjects.push({
    id: catalogId,
    content: `<< /Type /Catalog /Pages ${pagesId} 0 R >>`,
  });

  // Sort by id
  pdfObjects.sort((a, b) => a.id - b.id);

  // Build PDF string
  const offsetMap: number[] = new Array(objId).fill(0);
  let bytePos = encoder.encode(pdf).length;

  for (const obj of pdfObjects) {
    offsetMap[obj.id] = bytePos;
    const objStr = `${obj.id} 0 obj\n${obj.content}\nendobj\n`;
    pdf += objStr;
    bytePos += encoder.encode(objStr).length;
  }

  // xref
  const xrefPos = bytePos;
  pdf += `xref\n0 ${objId}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i < objId; i++) {
    pdf += `${String(offsetMap[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objId} /Root ${catalogId} 0 R >>\n`;
  pdf += `startxref\n${xrefPos}\n%%EOF`;

  return encoder.encode(pdf);
}
